const post = [
  {
    id: 1,
    image: "image-post.gif",
    accountImage: "account.gif",
    name: "Trần Khoa",
    time: "1",
    likes: [
      { id: 1, imageAccount: "/account.gif", nameAccount: "David" },
      { id: 2, imageAccount: "/account2.gif", nameAccount: "Steven" },
      { id: 3, imageAccount: "/account3.gif", nameAccount: "David" },
      { id: 4, imageAccount: "/account4.gif", nameAccount: "buffalo" },
      { id: 5, imageAccount: "/account.gif", nameAccount: "David" },
      { id: 6, imageAccount: "/account2.gif", nameAccount: "Steven" },
      { id: 7, imageAccount: "/account3.gif", nameAccount: "David" },
      { id: 8, imageAccount: "/account4.gif", nameAccount: "buffalo" },
    ],
  },
  {
    id: 2,
    image: "account2.gif",
    accountImage: "account2.gif",
    name: "Steven",
    time: "2",
    likes: [
      { id: 1, imageAccount: "/account2.gif", nameAccount: "David" },
      { id: 2, imageAccount: "/account4.gif", nameAccount: "Steven" },
      { id: 3, imageAccount: "/account.gif", nameAccount: "David" },
      { id: 4, imageAccount: "/account4.gif", nameAccount: "buffalo" },
      { id: 5, imageAccount: "/account3.gif", nameAccount: "David" },
      { id: 6, imageAccount: "/account.gif", nameAccount: "Steven" },
      { id: 7, imageAccount: "/account4.gif", nameAccount: "David" },
      { id: 8, imageAccount: "/account2.gif", nameAccount: "buffalo" },
    ],
  },
  {
    id: 3,
    image: "image-post2.gif",
    accountImage: "account3.gif",
    name: "David",
    time: "1",
    likes: [
      { id: 1, imageAccount: "/account3.gif", nameAccount: "David" },
      { id: 2, imageAccount: "/account4.gif", nameAccount: "Steven" },
      { id: 3, imageAccount: "/account2.gif", nameAccount: "David" },
      { id: 4, imageAccount: "/account4.gif", nameAccount: "buffalo" },
      { id: 5, imageAccount: "/account.gif", nameAccount: "David" },
      { id: 6, imageAccount: "/account3.gif", nameAccount: "Steven" },
      { id: 7, imageAccount: "/account2.gif", nameAccount: "David" },
      { id: 8, imageAccount: "/account4.gif", nameAccount: "buffalo" },
    ],
  },
  {
    id: 4,
    image: "image-post3.gif",
    accountImage: "account4.gif",
    name: "buffalo",
    time: "2",
    likes: [
      { id: 1, imageAccount: "/account.gif", nameAccount: "David" },
      { id: 2, imageAccount: "/account2.gif", nameAccount: "Steven" },
      { id: 3, imageAccount: "/account3.gif", nameAccount: "David" },
      { id: 4, imageAccount: "/account4.gif", nameAccount: "buffalo" },
      { id: 5, imageAccount: "/account.gif", nameAccount: "David" },
      { id: 6, imageAccount: "/account2.gif", nameAccount: "Steven" },
      { id: 7, imageAccount: "/account3.gif", nameAccount: "David" },
      { id: 8, imageAccount: "/account4.gif", nameAccount: "buffalo" },
    ],
  },
];

export default post;